version: '3.9'

x-logging:
    &default-logging
    options:
        max-size: '200k'
        max-file: '5'
    driver: json-file


services:
        
    tableau-online-usage:
        build: ./
        image: tableau-online-usage-image
        container_name: tableau-online-usage-container
        env_file: ./.env
        logging: *default-logging
        volumes:
            - tou:/usr/src/tableau_online_usage

volumes:
    tou:
        external: true